# Generated by Django 5.2 on 2025-12-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='sort_order',
            field=models.IntegerField(null=True),
        ),
    ]
