# Generated by Django 5.2 on 2026-01-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
